import type { NextPage } from "next"
import Head from "next/head"
import LandingPage from "../components/LandingPage"
import About from "../components/About"
import Projects from "../components/Projects"
import { PageContext } from "../utils/pageContext"
import { useState, useEffect } from "react"
import { AnimatePresence } from "framer-motion"

const Home: NextPage = () => {
  const [page, setPage] = useState("Projects")
  const [contextChange, setContextChange] = useState(true)

  useEffect(() => {
    setContextChange(false)
    return () => {
      setContextChange(true)
    }
  }, [])

  return (
    <PageContext.Provider value={{ page, setPage, contextChange, setContextChange }}>
      <div className="w-full h-screen bg-black flex flex-col justify-start items-center">
        <title>Elias Tracy</title>
        <Head>
          <meta name="Elias Tracy's Portfolio Website" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <AnimatePresence>
          {
            {
              Landing: <LandingPage key="Landing" />,
              Projects: <Projects key="Projects" />,
              About: <About key="About" />,
              Contact: (
                <div className="w-full h-full flex justify-center items-center">
                  <h1 className="text-black">I am the contact page</h1>
                </div>
              )
            }[page]
          }
        </AnimatePresence>
      </div>
    </PageContext.Provider>
  )
}

export default Home
