import type { NextPage } from "next"
import Head from "next/head"
import LandingPage from "../components/LandingPage"
import About from "../components/About"
import Projects from "../components/Projects"
import Resume from "../components/Resume"
import Contact from "../components/Contact"
import { PageContext } from "../utils/pageContext"
import { useState, useEffect } from "react"
import { AnimatePresence } from "framer-motion"

const Index: NextPage = () => {
  const [page, setPage] = useState("Home")
  const [contextChange, setContextChange] = useState(true)

  useEffect(() => {
    setContextChange(false)
    return () => {
      setContextChange(true)
    }
  }, [])

  return (
    <PageContext.Provider value={{ page, setPage, contextChange, setContextChange }}>
      <div className="w-full h-screen bg-black flex flex-col justify-start items-center">
        <title>Elias Tracy</title>
        <Head>
          <meta name="Elias Tracy's Portfolio Website" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <AnimatePresence>
          {
            {
              Home: <LandingPage key="Landing Page" />,
              Projects: <Projects key="Projects" />,
              About: <About key="About" />,
              Contact: <Contact />,
              Resume: <Resume key="Resume" />
            }[page]
          }
        </AnimatePresence>
      </div>
    </PageContext.Provider>
  )
}

export default Index
